GET http://localhost:8082/business/hello
Accept: application/json
###
GET http://localhost:8000/business/hello
Accept: application/json
###
GET http://localhost:8000/business/admin/train/gen-seat/G33
Accept: application/json
###
GET http://localhost:8000/business/admin/train/query-all
Accept: application/json
###
GET http://localhost:8000/business/admin/daily-train-ticket/query-list?page=1&size=5
    &trainCode=G33&start=乐清&end=淮安
Accept: application/json
###
GET http://localhost:8000/business/admin/daily-train-ticket/query-list3?page=1&size=5
    &trainCode=G33&start=乐清&end=淮安
Accept: application/json
###
POST http://localhost:8000/business/confirm-order/do
Content-Type: application/json
token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3MzMxOTE1NzksIm1vYmlsZSI6IjEzMzYyNzcwNzYyIiwiaWQiOjE4NTM5Nzc1NTIwNjcxMDQ3NjgsImV4cCI6MTczMzI3Nzk3OSwiaWF0IjoxNzMzMTkxNTc5fQ.AprryIA9TjcJNS54vD7Nw5xVOzmBjFwXzXL8tzyvAtM

{
  "dailyTrainTicketId":1857345564920909824,
  "date":1730390400000,
  "end":"淮安",
  "start":"菏泽",
  "tickets":[
    {"passengerId":1857306695735316480,
      "passengerIdCard":"123456",
      "passengerName":"hbh",
      "passengerType":"1",
      "seatTypeCode":"2"
    }],
  "trainCode":"G33"
}


###